<a href="https://colab.research.google.com/github/afllaabdi/tugas_NLP/blob/main/NLP(definitive_edition)ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **DATA CLEANING**

In [1]:
# =========================
# INSTALL LIBRARY (JALANKAN SEKALI)
# =========================
!pip install Sastrawi

Requirement already satisfied: Sastrawi in /usr/local/lib/python3.12/dist-packages (1.0.1)

Pada tahap ini, kami menggunakan library Sastrawi untuk melakukan proses stemming pada teks bahasa Indonesia. Library ini dipilih karena mampu mengubah kata berimbuhan menjadi kata dasar secara akurat.

In [2]:
# =========================
# IMPORT LIBRARY
# =========================
import pandas as pd
import re

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

# =========================
# MOUNT GOOGLE DRIVE
# =========================
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Pada tahap ini, kami menggunakan beberapa library utama, yaitu:

- pandas untuk mengelola dan memproses dataset
- re untuk melakukan pembersihan teks menggunakan regular expression
- Sastrawi untuk proses stemming

Selain itu, kami menghubungkan Google Colab dengan Google Drive agar dataset dapat diakses secara langsung.

In [3]:
# =========================
# LOAD DATA
# =========================
file_path = '/content/drive/MyDrive/dataset/news_title_filter.csv'

df = pd.read_csv(file_path)

print("Jumlah data:", df.shape)
df.head(5)

Jumlah data: (4444, 4)

,date,url,title,category
0,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...",finance
1,02/26/2020,https://finance.detik.com/properti/d-4915865/j...,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,finance
2,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Banyak Slot Penerbangan Internasional Kosong, ...",finance
3,02/26/2020,https://finance.detik.com/energi/d-4915883/atu...,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,finance
4,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo",finance

Pada tahap ini, kami memuat dataset dari Google Drive menggunakan library pandas. Dataset yang digunakan berisi judul berita yang akan diproses lebih lanjut. Kami juga menampilkan sebagian data untuk memahami struktur awal dataset.

In [4]:
# =========================
# COPY DATA
# =========================
df['clean_text'] = df['title']

df[['title', 'clean_text']].head()

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...","Terbitkan Resi Pertama, SRG Konawe Bantu Ketah..."
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...
2,"Banyak Slot Penerbangan Internasional Kosong, ...","Banyak Slot Penerbangan Internasional Kosong, ..."
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo","Izin Impor Lelet, Waspada Ekspor RI Makin Loyo"

Pada tahap ini, kami membuat salinan dari kolom title ke kolom baru clean_text. Hal ini dilakukan agar data asli tetap terjaga dan proses cleaning hanya dilakukan pada kolom hasil salinan.

In [5]:
# =========================
# LOWERCASE
# =========================
df['clean_text'] = df['clean_text'].str.lower()

df[['title', 'clean_text']].head(100)

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...","terbitkan resi pertama, srg konawe bantu ketah..."
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka 3 juta lapangan kerja di ibu...
2,"Banyak Slot Penerbangan Internasional Kosong, ...","banyak slot penerbangan internasional kosong, ..."
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,aturan wajib penggunaan kapal ri bisa ganggu e...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo","izin impor lelet, waspada ekspor ri makin loyo"
...,...,...
95,"Harga Pangan Melonjak di Tengah Corona, Ini Bi...","harga pangan melonjak di tengah corona, ini bi..."
96,"Siasati Dampak Corona, Peternak Jual Ayam Door...","siasati dampak corona, peternak jual ayam door..."
97,"Surplus Sekitar 128.000 Ton, Persediaan Beras ...","surplus sekitar 128.000 ton, persediaan beras ..."
98,"Tak Perlu Keluar Rumah, Urus Izin Impor Pakan ...","tak perlu keluar rumah, urus izin impor pakan ..."
99,"Naik Rp 32.000, Harga Emas Makin Dekat Rp 1 Ju...","naik rp 32.000, harga emas makin dekat rp 1 ju..."

Kami menggunakan lowercase untuk menyamakan format teks agar konsisten.

In [6]:
# =========================
# HITUNG JUMLAH NOISE SEBELUM DIHAPUS
# =========================
jumlah_video = df['clean_text'].str.count('video:').sum()
jumlah_foto = df['clean_text'].str.count('foto:').sum()

print(f"Jumlah 'video:' sebelum dihapus: {jumlah_video}")
print(f"Jumlah 'foto:' sebelum dihapus: {jumlah_foto}")
print(f"Total noise: {jumlah_video + jumlah_foto}")

Jumlah 'video:' sebelum dihapus: 3
Jumlah 'foto:' sebelum dihapus: 8
Total noise: 11

In [7]:
# =========================
# HAPUS NOISE
# =========================
df['clean_text'] = df['clean_text'].str.replace('video:', '', regex=False)
df['clean_text'] = df['clean_text'].str.replace('foto:', '', regex=False)

df[['title', 'clean_text']].head(5)

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...","terbitkan resi pertama, srg konawe bantu ketah..."
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka 3 juta lapangan kerja di ibu...
2,"Banyak Slot Penerbangan Internasional Kosong, ...","banyak slot penerbangan internasional kosong, ..."
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,aturan wajib penggunaan kapal ri bisa ganggu e...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo","izin impor lelet, waspada ekspor ri makin loyo"

Pada tahap ini, kami menghapus kata-kata yang dianggap sebagai noise. Kata-kata tersebut tidak memiliki makna penting dalam analisis sehingga perlu dihilangkan.

In [8]:
# =========================
# HITUNG JUMLAH NOISE SETELAH DIHAPUS
# =========================
jumlah_video_after = df['clean_text'].str.count('video:').sum()
jumlah_foto_after = df['clean_text'].str.count('foto:').sum()

print(f"Jumlah 'video:' setelah dihapus: {jumlah_video_after}")
print(f"Jumlah 'foto:' setelah dihapus: {jumlah_foto_after}")
print(f"Total noise setelah dihapus: {jumlah_video_after + jumlah_foto_after}")

Jumlah 'video:' setelah dihapus: 0
Jumlah 'foto:' setelah dihapus: 0
Total noise setelah dihapus: 0

In [9]:
# =========================
# HAPUS ANGKA
# =========================
df['clean_text'] = df['clean_text'].apply(lambda x: re.sub(r'\d+', '', str(x)))

df[['title', 'clean_text']].head()

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...","terbitkan resi pertama, srg konawe bantu ketah..."
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka juta lapangan kerja di ibu ...
2,"Banyak Slot Penerbangan Internasional Kosong, ...","banyak slot penerbangan internasional kosong, ..."
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,aturan wajib penggunaan kapal ri bisa ganggu e...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo","izin impor lelet, waspada ekspor ri makin loyo"

Pada tahap ini, kami menghapus seluruh angka dari teks karena angka tidak memberikan kontribusi signifikan dalam analisis berbasis teks.

In [10]:
# =========================
# HAPUS SIMBOL
# =========================
df['clean_text'] = df['clean_text'].apply(lambda x: re.sub(r'[^a-zA-Z\s]', '', x))

df[['title', 'clean_text']].head()

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...",terbitkan resi pertama srg konawe bantu ketaha...
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka juta lapangan kerja di ibu ...
2,"Banyak Slot Penerbangan Internasional Kosong, ...",banyak slot penerbangan internasional kosong i...
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,aturan wajib penggunaan kapal ri bisa ganggu e...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo",izin impor lelet waspada ekspor ri makin loyo

Pada tahap ini, kami menghapus karakter selain huruf dan spasi, seperti tanda baca dan simbol. Hal ini dilakukan untuk memastikan bahwa teks hanya berisi kata-kata yang relevan.

In [11]:
# =========================
# HAPUS SPASI BERLEBIH
# =========================
df['clean_text'] = df['clean_text'].apply(lambda x: re.sub(r'\s+', ' ', x).strip())

df[['title', 'clean_text']].head()

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...",terbitkan resi pertama srg konawe bantu ketaha...
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka juta lapangan kerja di ibu k...
2,"Banyak Slot Penerbangan Internasional Kosong, ...",banyak slot penerbangan internasional kosong i...
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,aturan wajib penggunaan kapal ri bisa ganggu e...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo",izin impor lelet waspada ekspor ri makin loyo

Pada tahap ini, kami melakukan normalisasi spasi dengan menghapus spasi berlebih agar teks menjadi lebih rapi dan konsisten.

In [12]:
# =========================
# STEMMING
# =========================
factory = StemmerFactory()
stemmer = factory.create_stemmer()

df['clean_text'] = df['clean_text'].apply(lambda x: stemmer.stem(x))

df[['title', 'clean_text']].head(5)

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...",terbit resi pertama srg konawe bantu tahan pan...
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka juta lapang kerja di ibu kot...
2,"Banyak Slot Penerbangan Internasional Kosong, ...",banyak slot terbang internasional kosong ini l...
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,atur wajib guna kapal ri bisa ganggu ekspor ba...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo",izin impor lelet waspada ekspor ri makin loyo

Pada tahap ini, kami menggunakan algoritma stemming dengan library Sastrawi untuk mengubah kata menjadi bentuk dasar. Proses ini bertujuan untuk menyederhanakan variasi kata sehingga memiliki representasi yang sama.

In [13]:
# =========================
# HAPUS STOPWORDS (KATA PENGHUBUNG)
# =========================
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

factory = StopWordRemoverFactory()
stopword = factory.create_stop_word_remover()

df['clean_text'] = df['clean_text'].apply(lambda x: stopword.remove(x))

df[['title', 'clean_text']].head(5)

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...",terbit resi pertama srg konawe bantu tahan pan...
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka juta lapang kerja ibu kota n...
2,"Banyak Slot Penerbangan Internasional Kosong, ...",banyak slot terbang internasional kosong langk...
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,atur wajib kapal ri ganggu ekspor batu bara
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo",izin impor lelet waspada ekspor ri makin loyo

In [14]:
# =========================
# HASIL CLEANING
# =========================
df[['title', 'clean_text']].head(10)

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...",terbit resi pertama srg konawe bantu tahan pan...
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka juta lapang kerja ibu kota n...
2,"Banyak Slot Penerbangan Internasional Kosong, ...",banyak slot terbang internasional kosong langk...
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,atur wajib kapal ri ganggu ekspor batu bara
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo",izin impor lelet waspada ekspor ri makin loyo
5,Inflasi Rendah Karena Daya Beli Turun? Ini Kat...,inflasi rendah daya beli turun kata bi
6,CT Bicara Inflasi Rendah: Ekonomi Membaik atau...,ct bicara inflasi rendah ekonomi baik daya bel...
7,"Usai Cetak Rekor, Harga Emas Antam Hari Ini Tu...",usai cetak rekor harga emas antam hari turun c...
8,Ekspor Impor Bisa Mandek Gara-gara Banjir,ekspor impor mandek garagara banjir
9,Diskon Liburan hingga Tambahan Rp 50.000 Kartu...,diskon libur hingga tambah rp kartu sembako te...

Pada tahap ini, kami menampilkan hasil akhir dari proses data cleaning untuk memastikan bahwa semua tahapan telah berjalan dengan baik.

In [15]:
# =========================
# SAVE DATA
# =========================
save_path = '/content/drive/MyDrive/dataset/dataset_clean_final.csv'

df.to_csv(save_path, index=False)

print("Dataset berhasil disimpan!")

Dataset berhasil disimpan!

Pada tahap ini, kami menyimpan hasil data cleaning ke dalam file CSV agar dapat digunakan pada tahap berikutnya, seperti transformasi atau pemodelan.

## **DATA TRANSFORM**

In [16]:
# =========================
# LOAD DATA
# =========================
import pandas as pd

file_path = '/content/drive/MyDrive/dataset/dataset_clean_final.csv'
df = pd.read_csv(file_path)

print("Jumlah data (baris, kolom):", df.shape)
df.head(4)

Jumlah data (baris, kolom): (4444, 5)

,date,url,title,category,clean_text
0,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...",finance,terbit resi pertama srg konawe bantu tahan pan...
1,02/26/2020,https://finance.detik.com/properti/d-4915865/j...,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,finance,jokowi janji buka juta lapang kerja ibu kota n...
2,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Banyak Slot Penerbangan Internasional Kosong, ...",finance,banyak slot terbang internasional kosong langk...
3,02/26/2020,https://finance.detik.com/energi/d-4915883/atu...,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,finance,atur wajib kapal ri ganggu ekspor batu bara

Pada tahap ini, kami memuat dataset hasil cleaning dan menampilkan 4 data pertama untuk melihat struktur awal data.

In [17]:
# =========================
# INFO DATASET
# =========================
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4444 entries, 0 to 4443
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        4444 non-null   object
 1   url         4444 non-null   object
 2   title       4444 non-null   object
 3   category    4444 non-null   object
 4   clean_text  4444 non-null   object
dtypes: object(5)
memory usage: 173.7+ KB

In [18]:
# =========================
# FEATURE EXTRACTION
# =========================

# Panjang teks (jumlah karakter)
df['text_length'] = df['clean_text'].apply(len)

# Jumlah kata
df['word_count'] = df['clean_text'].apply(lambda x: len(str(x).split()))

# Rata-rata panjang kata
df['avg_word_length'] = df['clean_text'].apply(
    lambda x: sum(len(word) for word in str(x).split()) / len(str(x).split())
    if len(str(x).split()) > 0 else 0
)

df[['clean_text', 'text_length', 'word_count', 'avg_word_length']].head(5)

,clean_text,text_length,word_count,avg_word_length
0,terbit resi pertama srg konawe bantu tahan pan...,58,9,5.555556
1,jokowi janji buka juta lapang kerja ibu kota n...,56,10,4.700000
2,banyak slot terbang internasional kosong langk...,55,7,7.000000
3,atur wajib kapal ri ganggu ekspor batu bara,43,8,4.500000
4,izin impor lelet waspada ekspor ri makin loyo,45,8,4.750000

Pada tahap ini, kami melakukan ekstraksi fitur dasar dari teks, yaitu:

- panjang teks
- jumlah kata
- rata-rata panjang kata

Fitur ini digunakan untuk merepresentasikan karakteristik teks dalam bentuk numerik.

In [21]:
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

factory = StopWordRemoverFactory()
stopwords = factory.get_stop_words()

In [31]:
# =========================
# BAG OF WORDS (1-GRAM)
# =========================
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import numpy as np

bow = CountVectorizer(ngram_range=(1,1), stop_words=stopwords)

bow_matrix = bow.fit_transform(df['clean_text'])

feature_names = bow.get_feature_names_out()

all_data = []

for i in range(5):
    row = bow_matrix[i].toarray().flatten()
    indices = np.where(row > 0)[0]

    for idx in indices:
        all_data.append([i, feature_names[idx], int(row[idx])])

bow_table = pd.DataFrame(all_data, columns=["Index", "Kata", "Frekuensi"])

bow_table = bow_table.reset_index(drop=True)

bow_table
bow_table

    Index           Kata  Frekuensi
0       0          bantu          1
1       0         konawe          1
2       0       nasional          1
3       0         pangan          1
4       0        pertama          1
5       0           resi          1
6       0            srg          1
7       0          tahan          1
8       0         terbit          1
9       1           baru          1
10      1           buka          1
11      1            ibu          1
12      1          janji          1
13      1         jokowi          1
14      1           juta          1
15      1          kerja          1
16      1           kota          1
17      1         lapang          1
18      1         negara          1
19      2         banyak          1
20      2  internasional          1
21      2         kosong          1
22      2        langkah          1
23      2         menhub          1
24      2           slot          1
25      2        terbang          1
26      3           atur          1
27      3           bara          1
28      3           batu          1
29      3         ekspor          1
30      3         ganggu          1
31      3          kapal          1
32      3             ri          1
33      3          wajib          1
34      4         ekspor          1
35      4          impor          1
36      4           izin          1
37      4          lelet          1
38      4           loyo          1
39      4          makin          1
40      4             ri          1
41      4        waspada          1

Pada tahap ini, kami menggunakan metode Bag of Words (1-gram) untuk mengubah teks menjadi representasi numerik berdasarkan frekuensi kemunculan kata.

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(df['clean_text'])

In [24]:
# =========================
# TF-IDF
# =========================
import pandas as pd
import numpy as np

feature_names = tfidf.get_feature_names_out()
top_n = 5

all_data = []

for i in range(5):  # 5 data sesuai tabel lo
    row = tfidf_matrix[i].toarray().flatten()
    top_indices = row.argsort()[-top_n:][::-1]

    for idx in top_indices:
        all_data.append([i, feature_names[idx], round(row[idx], 2)])

# jadi satu tabel
tfidf_table = pd.DataFrame(all_data, columns=["Index", "Kata", "TF-IDF"])

tfidf_table = tfidf_table.sort_values(by=["Index", "TF-IDF"], ascending=[True, False])
tfidf_table = tfidf_table.reset_index(drop=True)

tfidf_table

    Index           Kata  TF-IDF
0       0            srg    0.41
1       0           resi    0.41
2       0         konawe    0.39
3       0         terbit    0.34
4       0       nasional    0.34
5       1          janji    0.41
6       1            ibu    0.40
7       1         negara    0.34
8       1           kota    0.34
9       1          kerja    0.30
10      2           slot    0.47
11      2         menhub    0.40
12      2  internasional    0.40
13      2         kosong    0.39
14      2        terbang    0.38
15      3           bara    0.40
16      3           atur    0.39
17      3          kapal    0.39
18      3           batu    0.39
19      3          wajib    0.37
20      4          lelet    0.50
21      4           loyo    0.44
22      4        waspada    0.41
23      4           izin    0.35
24      4          makin    0.35

Pada tahap ini, kami menggunakan TF-IDF (Term Frequency - Inverse Document Frequency) untuk memberikan bobot pada kata berdasarkan tingkat kepentingannya dalam dokumen.

Pada tahap ini, kami menggunakan bigram (2-gram) untuk menangkap pasangan kata yang muncul secara berurutan dalam teks.

In [25]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import numpy as np

# BIGRAM
bigram = CountVectorizer(ngram_range=(2,2))
bigram_matrix = bigram.fit_transform(df['clean_text'])

feature_names = bigram.get_feature_names_out()

all_data = []

for i in range(5):  # ambil 5 data
    row = bigram_matrix[i].toarray().flatten()
    indices = np.where(row > 0)[0]

    for idx in indices:
        all_data.append([i, feature_names[idx], int(row[idx])])

bigram_table = pd.DataFrame(all_data, columns=["Index", "N-Gram", "Frekuensi"])

bigram_table = bigram_table.reset_index(drop=True)

bigram_table

    Index                 N-Gram  Frekuensi
0       0            bantu tahan          1
1       0           konawe bantu          1
2       0        pangan nasional          1
3       0            pertama srg          1
4       0           resi pertama          1
5       0             srg konawe          1
6       0           tahan pangan          1
7       0            terbit resi          1
8       1              buka juta          1
9       1               ibu kota          1
10      1             janji buka          1
11      1           jokowi janji          1
12      1            juta lapang          1
13      1              kerja ibu          1
14      1            kota negara          1
15      1           lapang kerja          1
16      1            negara baru          1
17      2            banyak slot          1
18      2   internasional kosong          1
19      2         kosong langkah          1
20      2         langkah menhub          1
21      2           slot terbang          1
22      2  terbang internasional          1
23      3             atur wajib          1
24      3              batu bara          1
25      3            ekspor batu          1
26      3          ganggu ekspor          1
27      3               kapal ri          1
28      3              ri ganggu          1
29      3            wajib kapal          1
30      4              ekspor ri          1
31      4            impor lelet          1
32      4             izin impor          1
33      4          lelet waspada          1
34      4             makin loyo          1
35      4               ri makin          1
36      4         waspada ekspor          1

In [26]:
# TRIGRAM
trigram = CountVectorizer(ngram_range=(3,3))
trigram_matrix = trigram.fit_transform(df['clean_text'])

feature_names = trigram.get_feature_names_out()

all_data = []

for i in range(5):  # ambil 5 data
    row = trigram_matrix[i].toarray().flatten()
    indices = np.where(row > 0)[0]

    for idx in indices:
        all_data.append([i, feature_names[idx], int(row[idx])])

trigram_table = pd.DataFrame(all_data, columns=["Index", "N-Gram", "Frekuensi"])

trigram_table = trigram_table.reset_index(drop=True)

trigram_table

    Index                        N-Gram  Frekuensi
0       0            bantu tahan pangan          1
1       0            konawe bantu tahan          1
2       0            pertama srg konawe          1
3       0              resi pertama srg          1
4       0              srg konawe bantu          1
5       0         tahan pangan nasional          1
6       0           terbit resi pertama          1
7       1              buka juta lapang          1
8       1               ibu kota negara          1
9       1               janji buka juta          1
10      1             jokowi janji buka          1
11      1             juta lapang kerja          1
12      1                kerja ibu kota          1
13      1              kota negara baru          1
14      1              lapang kerja ibu          1
15      2           banyak slot terbang          1
16      2  internasional kosong langkah          1
17      2         kosong langkah menhub          1
18      2    slot terbang internasional          1
19      2  terbang internasional kosong          1
20      3              atur wajib kapal          1
21      3              ekspor batu bara          1
22      3            ganggu ekspor batu          1
23      3               kapal ri ganggu          1
24      3              ri ganggu ekspor          1
25      3                wajib kapal ri          1
26      4               ekspor ri makin          1
27      4           impor lelet waspada          1
28      4              izin impor lelet          1
29      4          lelet waspada ekspor          1
30      4                 ri makin loyo          1
31      4             waspada ekspor ri          1

Pada tahap ini, kami menggunakan trigram (3-gram) untuk menangkap pola tiga kata berurutan dalam teks.

In [28]:
# =========================
# TOP WORDS
# =========================
word_counts = bow_matrix.sum(axis=0).A1
words = bow.get_feature_names_out()

top_words_df = pd.DataFrame({
    'word': words,
    'count': word_counts
}).sort_values(by='count', ascending=False)

top_words_df.head(10)

         word  count
1563    harga   1384
889    corona    643
3943       rp    496
4158  sembako    336
1718    impor    331
304      ayam    306
3874       ri    240
4889    turun    237
1171   ekspor    233
1507     gula    222

Pada tahap ini, kami mengidentifikasi kata yang paling sering muncul dalam dataset untuk memahami pola dominan dalam data.

In [29]:
# =========================
# SAVE DATA
# =========================
df.to_csv('/content/drive/MyDrive/dataset/dataset_transform_final.csv', index=False)

print("Dataset transformasi berhasil disimpan!")

Dataset transformasi berhasil disimpan!