<a href="https://colab.research.google.com/github/afllaabdi/tugas_NLP/blob/main/NLP(definitive_edition)ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **DATA CLEANING**

In [ ]:
# =========================
# INSTALL LIBRARY (JALANKAN SEKALI)
# =========================
!pip install Sastrawi

Collecting Sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl.metadata (909 bytes)
Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 5.2 MB/s eta 0:00:00
Installing collected packages: Sastrawi
Successfully installed Sastrawi-1.0.1

Pada tahap ini, kami menggunakan library Sastrawi untuk melakukan proses stemming pada teks bahasa Indonesia. Library ini dipilih karena mampu mengubah kata berimbuhan menjadi kata dasar secara akurat.

In [ ]:
# =========================
# IMPORT LIBRARY
# =========================
import pandas as pd
import re

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

# =========================
# MOUNT GOOGLE DRIVE
# =========================
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Pada tahap ini, kami menggunakan beberapa library utama, yaitu:

- pandas untuk mengelola dan memproses dataset
- re untuk melakukan pembersihan teks menggunakan regular expression
- Sastrawi untuk proses stemming

Selain itu, kami menghubungkan Google Colab dengan Google Drive agar dataset dapat diakses secara langsung.

In [ ]:
# =========================
# LOAD DATA
# =========================
file_path = '/content/drive/MyDrive/dataset/news_title_filter.csv'

df = pd.read_csv(file_path)

print("Jumlah data:", df.shape)
df.head(5)

Jumlah data: (4444, 4)

,date,url,title,category
0,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...",finance
1,02/26/2020,https://finance.detik.com/properti/d-4915865/j...,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,finance
2,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Banyak Slot Penerbangan Internasional Kosong, ...",finance
3,02/26/2020,https://finance.detik.com/energi/d-4915883/atu...,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,finance
4,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo",finance

Pada tahap ini, kami memuat dataset dari Google Drive menggunakan library pandas. Dataset yang digunakan berisi judul berita yang akan diproses lebih lanjut. Kami juga menampilkan sebagian data untuk memahami struktur awal dataset.

In [ ]:
# =========================
# COPY DATA
# =========================
df['clean_text'] = df['title']

df[['title', 'clean_text']].head()

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...","Terbitkan Resi Pertama, SRG Konawe Bantu Ketah..."
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...
2,"Banyak Slot Penerbangan Internasional Kosong, ...","Banyak Slot Penerbangan Internasional Kosong, ..."
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo","Izin Impor Lelet, Waspada Ekspor RI Makin Loyo"

Pada tahap ini, kami membuat salinan dari kolom title ke kolom baru clean_text. Hal ini dilakukan agar data asli tetap terjaga dan proses cleaning hanya dilakukan pada kolom hasil salinan.

In [ ]:
# =========================
# LOWERCASE
# =========================
df['clean_text'] = df['clean_text'].str.lower()

df[['title', 'clean_text']].head(100)

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...","terbitkan resi pertama, srg konawe bantu ketah..."
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka 3 juta lapangan kerja di ibu...
2,"Banyak Slot Penerbangan Internasional Kosong, ...","banyak slot penerbangan internasional kosong, ..."
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,aturan wajib penggunaan kapal ri bisa ganggu e...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo","izin impor lelet, waspada ekspor ri makin loyo"
...,...,...
95,"Harga Pangan Melonjak di Tengah Corona, Ini Bi...","harga pangan melonjak di tengah corona, ini bi..."
96,"Siasati Dampak Corona, Peternak Jual Ayam Door...","siasati dampak corona, peternak jual ayam door..."
97,"Surplus Sekitar 128.000 Ton, Persediaan Beras ...","surplus sekitar 128.000 ton, persediaan beras ..."
98,"Tak Perlu Keluar Rumah, Urus Izin Impor Pakan ...","tak perlu keluar rumah, urus izin impor pakan ..."
99,"Naik Rp 32.000, Harga Emas Makin Dekat Rp 1 Ju...","naik rp 32.000, harga emas makin dekat rp 1 ju..."

Kami menggunakan lowercase untuk menyamakan format teks agar konsisten.

In [ ]:
# =========================
# HITUNG JUMLAH NOISE SEBELUM DIHAPUS
# =========================
jumlah_video = df['clean_text'].str.count('video:').sum()
jumlah_foto = df['clean_text'].str.count('foto:').sum()

print(f"Jumlah 'video:' sebelum dihapus: {jumlah_video}")
print(f"Jumlah 'foto:' sebelum dihapus: {jumlah_foto}")
print(f"Total noise: {jumlah_video + jumlah_foto}")

Jumlah 'video:' sebelum dihapus: 3
Jumlah 'foto:' sebelum dihapus: 8
Total noise: 11

In [ ]:
# =========================
# HAPUS NOISE
# =========================
df['clean_text'] = df['clean_text'].str.replace('video:', '', regex=False)
df['clean_text'] = df['clean_text'].str.replace('foto:', '', regex=False)

df[['title', 'clean_text']].head(5)

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...","terbitkan resi pertama, srg konawe bantu ketah..."
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka 3 juta lapangan kerja di ibu...
2,"Banyak Slot Penerbangan Internasional Kosong, ...","banyak slot penerbangan internasional kosong, ..."
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,aturan wajib penggunaan kapal ri bisa ganggu e...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo","izin impor lelet, waspada ekspor ri makin loyo"

Pada tahap ini, kami menghapus kata-kata yang dianggap sebagai noise. Kata-kata tersebut tidak memiliki makna penting dalam analisis sehingga perlu dihilangkan.

In [ ]:
# =========================
# HITUNG JUMLAH NOISE SETELAH DIHAPUS
# =========================
jumlah_video_after = df['clean_text'].str.count('video:').sum()
jumlah_foto_after = df['clean_text'].str.count('foto:').sum()

print(f"Jumlah 'video:' setelah dihapus: {jumlah_video_after}")
print(f"Jumlah 'foto:' setelah dihapus: {jumlah_foto_after}")
print(f"Total noise setelah dihapus: {jumlah_video_after + jumlah_foto_after}")

Jumlah 'video:' setelah dihapus: 0
Jumlah 'foto:' setelah dihapus: 0
Total noise setelah dihapus: 0

In [ ]:
# =========================
# HAPUS ANGKA
# =========================
df['clean_text'] = df['clean_text'].apply(lambda x: re.sub(r'\d+', '', str(x)))

df[['title', 'clean_text']].head()

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...","terbitkan resi pertama, srg konawe bantu ketah..."
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka juta lapangan kerja di ibu ...
2,"Banyak Slot Penerbangan Internasional Kosong, ...","banyak slot penerbangan internasional kosong, ..."
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,aturan wajib penggunaan kapal ri bisa ganggu e...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo","izin impor lelet, waspada ekspor ri makin loyo"

Pada tahap ini, kami menghapus seluruh angka dari teks karena angka tidak memberikan kontribusi signifikan dalam analisis berbasis teks.

In [ ]:
# =========================
# HAPUS SIMBOL
# =========================
df['clean_text'] = df['clean_text'].apply(lambda x: re.sub(r'[^a-zA-Z\s]', '', x))

df[['title', 'clean_text']].head()

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...",terbitkan resi pertama srg konawe bantu ketaha...
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka juta lapangan kerja di ibu ...
2,"Banyak Slot Penerbangan Internasional Kosong, ...",banyak slot penerbangan internasional kosong i...
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,aturan wajib penggunaan kapal ri bisa ganggu e...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo",izin impor lelet waspada ekspor ri makin loyo

Pada tahap ini, kami menghapus karakter selain huruf dan spasi, seperti tanda baca dan simbol. Hal ini dilakukan untuk memastikan bahwa teks hanya berisi kata-kata yang relevan.

In [ ]:
# =========================
# HAPUS SPASI BERLEBIH
# =========================
df['clean_text'] = df['clean_text'].apply(lambda x: re.sub(r'\s+', ' ', x).strip())

df[['title', 'clean_text']].head()

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...",terbitkan resi pertama srg konawe bantu ketaha...
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka juta lapangan kerja di ibu k...
2,"Banyak Slot Penerbangan Internasional Kosong, ...",banyak slot penerbangan internasional kosong i...
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,aturan wajib penggunaan kapal ri bisa ganggu e...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo",izin impor lelet waspada ekspor ri makin loyo

Pada tahap ini, kami melakukan normalisasi spasi dengan menghapus spasi berlebih agar teks menjadi lebih rapi dan konsisten.

In [ ]:
# =========================
# STEMMING
# =========================
factory = StemmerFactory()
stemmer = factory.create_stemmer()

df['clean_text'] = df['clean_text'].apply(lambda x: stemmer.stem(x))

df[['title', 'clean_text']].head(5)

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...",terbit resi pertama srg konawe bantu tahan pan...
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka juta lapang kerja di ibu kot...
2,"Banyak Slot Penerbangan Internasional Kosong, ...",banyak slot terbang internasional kosong ini l...
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,atur wajib guna kapal ri bisa ganggu ekspor ba...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo",izin impor lelet waspada ekspor ri makin loyo

Pada tahap ini, kami menggunakan algoritma stemming dengan library Sastrawi untuk mengubah kata menjadi bentuk dasar. Proses ini bertujuan untuk menyederhanakan variasi kata sehingga memiliki representasi yang sama.

In [ ]:
# =========================
# HASIL CLEANING
# =========================
df[['title', 'clean_text']].head(10)

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...",terbit resi pertama srg konawe bantu tahan pan...
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka juta lapang kerja di ibu kot...
2,"Banyak Slot Penerbangan Internasional Kosong, ...",banyak slot terbang internasional kosong ini l...
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,atur wajib guna kapal ri bisa ganggu ekspor ba...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo",izin impor lelet waspada ekspor ri makin loyo
5,Inflasi Rendah Karena Daya Beli Turun? Ini Kat...,inflasi rendah karena daya beli turun ini kata bi
6,CT Bicara Inflasi Rendah: Ekonomi Membaik atau...,ct bicara inflasi rendah ekonomi baik atau day...
7,"Usai Cetak Rekor, Harga Emas Antam Hari Ini Tu...",usai cetak rekor harga emas antam hari ini tur...
8,Ekspor Impor Bisa Mandek Gara-gara Banjir,ekspor impor bisa mandek garagara banjir
9,Diskon Liburan hingga Tambahan Rp 50.000 Kartu...,diskon libur hingga tambah rp kartu sembako de...

Pada tahap ini, kami menampilkan hasil akhir dari proses data cleaning untuk memastikan bahwa semua tahapan telah berjalan dengan baik.

In [ ]:
# =========================
# SAVE DATA
# =========================
save_path = '/content/drive/MyDrive/dataset/dataset_clean_final.csv'

df.to_csv(save_path, index=False)

print("Dataset berhasil disimpan!")

Dataset berhasil disimpan!

Pada tahap ini, kami menyimpan hasil data cleaning ke dalam file CSV agar dapat digunakan pada tahap berikutnya, seperti transformasi atau pemodelan.

## **DATA TRANSFORM**

In [ ]:
# =========================
# LOAD DATA
# =========================
import pandas as pd

file_path = '/content/drive/MyDrive/dataset/dataset_clean_final.csv'
df = pd.read_csv(file_path)

print("Jumlah data (baris, kolom):", df.shape)
df.head(4)

Jumlah data (baris, kolom): (4444, 5)

,date,url,title,category,clean_text
0,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...",finance,terbitkan resi pertama srg konawe bantu ketaha...
1,02/26/2020,https://finance.detik.com/properti/d-4915865/j...,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,finance,jokowi janji buka juta lapangan kerja di ibu k...
2,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Banyak Slot Penerbangan Internasional Kosong, ...",finance,banyak slot penerbangan internasional kosong i...
3,02/26/2020,https://finance.detik.com/energi/d-4915883/atu...,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,finance,aturan wajib penggunaan kapal ri bisa ganggu e...

Pada tahap ini, kami memuat dataset hasil cleaning dan menampilkan 4 data pertama untuk melihat struktur awal data.

In [ ]:
# =========================
# INFO DATASET
# =========================
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4444 entries, 0 to 4443
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        4444 non-null   object
 1   url         4444 non-null   object
 2   title       4444 non-null   object
 3   category    4444 non-null   object
 4   clean_text  4444 non-null   object
dtypes: object(5)
memory usage: 173.7+ KB

In [ ]:
# =========================
# FEATURE EXTRACTION
# =========================

# Panjang teks (jumlah karakter)
df['text_length'] = df['clean_text'].apply(len)

# Jumlah kata
df['word_count'] = df['clean_text'].apply(lambda x: len(str(x).split()))

# Rata-rata panjang kata
df['avg_word_length'] = df['clean_text'].apply(
    lambda x: sum(len(word) for word in str(x).split()) / len(str(x).split())
    if len(str(x).split()) > 0 else 0
)

df[['clean_text', 'text_length', 'word_count', 'avg_word_length']].head(5)

,clean_text,text_length,word_count,avg_word_length
0,terbitkan resi pertama srg konawe bantu ketaha...,65,9,6.333333
1,jokowi janji buka juta lapangan kerja di ibu k...,61,11,4.636364
2,banyak slot penerbangan internasional kosong i...,63,8,7.000000
3,aturan wajib penggunaan kapal ri bisa ganggu e...,61,10,5.200000
4,izin impor lelet waspada ekspor ri makin loyo,45,8,4.750000

Pada tahap ini, kami melakukan ekstraksi fitur dasar dari teks, yaitu:

- panjang teks
- jumlah kata
- rata-rata panjang kata

Fitur ini digunakan untuk merepresentasikan karakteristik teks dalam bentuk numerik.

In [ ]:
# =========================
# BAG OF WORDS (1-GRAM)
# =========================
from sklearn.feature_extraction.text import CountVectorizer

bow = CountVectorizer(ngram_range=(1,1))
bow_matrix = bow.fit_transform(df['clean_text'])

bow_df = pd.DataFrame(bow_matrix.toarray(), columns=bow.get_feature_names_out())

bow_df.head(4)

,abah,abaikan,abang,abangabang,abarth,abg,abidin,abigail,abipraya,abk,...,ziudith,zohri,zombie,zon,zona,zoological,zoom,zs,zuckerberg,zxr
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Pada tahap ini, kami menggunakan metode Bag of Words (1-gram) untuk mengubah teks menjadi representasi numerik berdasarkan frekuensi kemunculan kata.

In [1]:
# =========================
# TF-IDF
# =========================
import pandas as pd
import numpy as np

feature_names = tfidf.get_feature_names_out()

top_n = 5

for i in range(4):
    row = tfidf_matrix[i].toarray().flatten()
    top_indices = row.argsort()[-top_n:][::-1]

    data = []
    for idx in top_indices:
        data.append([feature_names[idx], row[idx]])

    df_top = pd.DataFrame(data, columns=["Kata", "TF-IDF"])

    print(f"\nDokumen {i}")
    print(df_top)

NameError: name 'tfidf' is not defined

Pada tahap ini, kami menggunakan TF-IDF (Term Frequency - Inverse Document Frequency) untuk memberikan bobot pada kata berdasarkan tingkat kepentingannya dalam dokumen.

In [ ]:
# =========================
# BIGRAM (2-GRAM)
# =========================
feature_names = bigram.get_feature_names_out()

top_n = 5

for i in range(4):
    row = bigram_matrix[i].toarray().flatten()
    top_indices = row.argsort()[-top_n:][::-1]

    data = []
    for idx in top_indices:
        if row[idx] > 0:  # ambil yang muncul aja
            data.append([feature_names[idx], row[idx]])

    df_top = pd.DataFrame(data, columns=["Bigram", "Frekuensi"])

    print(f"\nDokumen {i}")
    print(df_top)

,abah disemayamkan,abaikan physical,abang dinsos,abang none,abang ojol,abangabang ala,abangabang yang,abarth si,abg di,abidin aceh,...,zombie ini,zon kritik,zon prabowo,zona merah,zoological garden,zoom kami,zs dengan,zs resmi,zuckerberg untuk,zxr segini
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Pada tahap ini, kami menggunakan bigram (2-gram) untuk menangkap pasangan kata yang muncul secara berurutan dalam teks.

In [ ]:
# =========================
# TRIGRAM (3-GRAM)
# =========================
trigram = CountVectorizer(ngram_range=(3,3))
trigram_matrix = trigram.fit_transform(df['clean_text'])

trigram_df = pd.DataFrame(trigram_matrix.toarray(), columns=trigram.get_feature_names_out())

trigram_df.head(4)

,abah disemayamkan di,abaikan physical distancing,abang dinsos sudah,abang none beri,abang ojol merasa,abangabang ala ayu,abangabang yang gurih,abarth si mungil,abg di tana,abidin aceh dipulangkan,...,zohri dkk dipulangkan,zombie ini hidup,zon kritik jokowi,zon prabowo bilang,zona merah corona,zoom kami salah,zs dengan honda,zs resmi meluncur,zuckerberg untuk covid,zxr segini bocoran
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# 1. Pilih baris yang mau dicek (misal baris index 0)
sample_row = tfidf_df.iloc[0]

# 2. Filter hanya kolom yang nilainya lebih dari 0
non_zero_values = sample_row[sample_row > 0]

# 3. Urutkan dari bobot tertinggi agar lebih enak dibaca
print("Kata-kata yang memiliki bobot di baris index 0:")
print(non_zero_values.sort_values(ascending=False))

Kata-kata yang memiliki bobot di baris index 0:
srg          0.387283
resi         0.387283
konawe       0.369247
terbitkan    0.369247
ketahanan    0.356450
nasional     0.320378
pertama      0.300724
bantu        0.273188
pangan       0.180475
Name: 0, dtype: float64

Pada tahap ini, kami menggunakan trigram (3-gram) untuk menangkap pola tiga kata berurutan dalam teks.

In [ ]:
# =========================
# TOP WORDS
# =========================
word_counts = bow_matrix.sum(axis=0).A1
words = bow.get_feature_names_out()

top_words_df = pd.DataFrame({
    'word': words,
    'count': word_counts
}).sort_values(by='count', ascending=False)

top_words_df.head(10)

         word  count
1590    harga   1384
1040       di   1115
901    corona    643
1782      ini    597
3999       rp    496
960       dan    416
2151       ke    377
5200     yang    342
4222  sembako    336
1746    impor    331

Pada tahap ini, kami mengidentifikasi kata yang paling sering muncul dalam dataset untuk memahami pola dominan dalam data.

In [ ]:
# =========================
# SAVE DATA
# =========================
df.to_csv('/content/drive/MyDrive/dataset/dataset_transform_final.csv', index=False)

print("Dataset transformasi berhasil disimpan!")

Dataset transformasi berhasil disimpan!