<a href="https://colab.research.google.com/github/afllaabdi/tugas_NLP/blob/main/Source_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# =========================
# IMPORT LIBRARY
# =========================
import pandas as pd
import re

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# =========================
# LOAD DATA
# =========================
file_path = '/content/drive/MyDrive/dataset/news_title_filter.csv'

df = pd.read_csv(file_path)

print("Jumlah data:", df.shape)
df.head(5)

Jumlah data: (4444, 4)

,date,url,title,category
0,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...",finance
1,02/26/2020,https://finance.detik.com/properti/d-4915865/j...,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,finance
2,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Banyak Slot Penerbangan Internasional Kosong, ...",finance
3,02/26/2020,https://finance.detik.com/energi/d-4915883/atu...,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,finance
4,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo",finance

In [ ]:
# =========================
# DATA CLEANING
# =========================
# =========================
# COPY DATA
# =========================
df['clean_text'] = df['title']

df[['title', 'clean_text']].head()

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...","Terbitkan Resi Pertama, SRG Konawe Bantu Ketah..."
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...
2,"Banyak Slot Penerbangan Internasional Kosong, ...","Banyak Slot Penerbangan Internasional Kosong, ..."
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo","Izin Impor Lelet, Waspada Ekspor RI Makin Loyo"

In [ ]:
# =========================
# LOWERCASE
# =========================
df['clean_text'] = df['clean_text'].str.lower()

df[['title', 'clean_text']].head(100)

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...","terbitkan resi pertama, srg konawe bantu ketah..."
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka 3 juta lapangan kerja di ibu...
2,"Banyak Slot Penerbangan Internasional Kosong, ...","banyak slot penerbangan internasional kosong, ..."
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,aturan wajib penggunaan kapal ri bisa ganggu e...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo","izin impor lelet, waspada ekspor ri makin loyo"
...,...,...
95,"Harga Pangan Melonjak di Tengah Corona, Ini Bi...","harga pangan melonjak di tengah corona, ini bi..."
96,"Siasati Dampak Corona, Peternak Jual Ayam Door...","siasati dampak corona, peternak jual ayam door..."
97,"Surplus Sekitar 128.000 Ton, Persediaan Beras ...","surplus sekitar 128.000 ton, persediaan beras ..."
98,"Tak Perlu Keluar Rumah, Urus Izin Impor Pakan ...","tak perlu keluar rumah, urus izin impor pakan ..."
99,"Naik Rp 32.000, Harga Emas Makin Dekat Rp 1 Ju...","naik rp 32.000, harga emas makin dekat rp 1 ju..."

In [ ]:
# Hitung jumlah noise sebelum dihapus
jumlah_video = df['clean_text'].str.count('video:').sum()
jumlah_foto = df['clean_text'].str.count('foto:').sum()

print(f"Jumlah 'video:' sebelum dihapus: {jumlah_video}")
print(f"Jumlah 'foto:' sebelum dihapus: {jumlah_foto}")
print(f"Total noise: {jumlah_video + jumlah_foto}")

Jumlah 'video:' sebelum dihapus: 0
Jumlah 'foto:' sebelum dihapus: 0
Total noise: 0

In [ ]:
# =========================
# HAPUS NOISE
# =========================
df['clean_text'] = df['clean_text'].str.replace('video:', '', regex=False)
df['clean_text'] = df['clean_text'].str.replace('foto:', '', regex=False)

df[['title', 'clean_text']].head(5)

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...","terbitkan resi pertama, srg konawe bantu ketah..."
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka 3 juta lapangan kerja di ibu...
2,"Banyak Slot Penerbangan Internasional Kosong, ...","banyak slot penerbangan internasional kosong, ..."
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,aturan wajib penggunaan kapal ri bisa ganggu e...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo","izin impor lelet, waspada ekspor ri makin loyo"

In [ ]:
# =========================
# HAPUS ANGKA
# =========================
df['clean_text'] = df['clean_text'].apply(lambda x: re.sub(r'\d+', '', x))

df[['title', 'clean_text']].head()

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...","terbitkan resi pertama, srg konawe bantu ketah..."
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka juta lapangan kerja di ibu ...
2,"Banyak Slot Penerbangan Internasional Kosong, ...","banyak slot penerbangan internasional kosong, ..."
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,aturan wajib penggunaan kapal ri bisa ganggu e...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo","izin impor lelet, waspada ekspor ri makin loyo"

In [ ]:
# =========================
# HAPUS SIMBOL
# =========================
df['clean_text'] = df['clean_text'].apply(lambda x: re.sub(r'[^a-zA-Z\s]', '', x))

df[['title', 'clean_text']].head()

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...",terbitkan resi pertama srg konawe bantu ketaha...
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka juta lapangan kerja di ibu ...
2,"Banyak Slot Penerbangan Internasional Kosong, ...",banyak slot penerbangan internasional kosong i...
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,aturan wajib penggunaan kapal ri bisa ganggu e...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo",izin impor lelet waspada ekspor ri makin loyo

In [ ]:
# =========================
# HAPUS SPASI
# =========================
df['clean_text'] = df['clean_text'].apply(lambda x: re.sub(r'\s+', ' ', x).strip())

df[['title', 'clean_text']].head()

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...",terbitkan resi pertama srg konawe bantu ketaha...
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka juta lapangan kerja di ibu k...
2,"Banyak Slot Penerbangan Internasional Kosong, ...",banyak slot penerbangan internasional kosong i...
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,aturan wajib penggunaan kapal ri bisa ganggu e...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo",izin impor lelet waspada ekspor ri makin loyo

In [ ]:
# =========================
# HASIL AKHIR CLEANING
# =========================
df[['title', 'clean_text']].sample(100)

,title,clean_text
4424,Harga Tiket Pesawat di China Turun Drastis hin...,harga tiket pesawat di china turun drastis hin...
1396,"Andre Lapor Buwas Tak Dapat Jatah Impor Gula, ...",andre lapor buwas tak dapat jatah impor gula i...
309,Draf Omnibus Law Cipta Lapangan Kerja Masuk DP...,draf omnibus law cipta lapangan kerja masuk dp...
1813,Punya Sisa Nasi dan Telur? Bisa Bikin Sahur En...,punya sisa nasi dan telur bisa bikin sahur ena...
1306,"Demi Stabilkan Harga, 50.000 Ton Gula Masuk RI...",demi stabilkan harga ton gula masuk ri hingga ...
...,...,...
3409,Terungkap Adanya Lobi 'Ibu Menteri' di Sidang ...,terungkap adanya lobi ibu menteri di sidang su...
1372,"Konflik AS-Iran Mereda, Harga Minyak Turun ke ...",konflik asiran mereda harga minyak turun ke us...
4253,"Beli Ducati Pakai Harga Off The Road, Gimana S...",beli ducati pakai harga off the road gimana su...
3596,Ngabalin Tegaskan Pemerintah Belum Ada Rencana...,ngabalin tegaskan pemerintah belum ada rencana...
4415,Pergerakan Mudik Terbesar Berasal dari Jawa Barat,pergerakan mudik terbesar berasal dari jawa barat

In [ ]:
# =========================
# SAVE DATA
file_save_path = '/content/drive/MyDrive/dataset/dataset_pangan_cleaning.csv'

df.to_csv(file_save_path, index=False)

print("Dataset berhasil disimpan!")

Dataset berhasil disimpan!

Tranformasi

In [ ]:
# =========================
# LOAD DATA
# =========================
file_path = '/content/drive/MyDrive/dataset/dataset_pangan_cleaning.csv'

df = pd.read_csv(file_path)

print("Jumlah data:", df.shape)
df.head(5)

Jumlah data: (4444, 5)

,date,url,title,category,clean_text
0,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...",finance,terbitkan resi pertama srg konawe bantu ketaha...
1,02/26/2020,https://finance.detik.com/properti/d-4915865/j...,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,finance,jokowi janji buka juta lapangan kerja di ibu k...
2,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Banyak Slot Penerbangan Internasional Kosong, ...",finance,banyak slot penerbangan internasional kosong i...
3,02/26/2020,https://finance.detik.com/energi/d-4915883/atu...,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,finance,aturan wajib penggunaan kapal ri bisa ganggu e...
4,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo",finance,izin impor lelet waspada ekspor ri makin loyo

In [ ]:
# =========================
# TEXT LENGTH
# =========================
df['text_length'] = df['clean_text'].apply(len)

df[['clean_text', 'text_length']].head()

                                          clean_text  text_length
0  terbitkan resi pertama srg konawe bantu ketaha...           65
1  jokowi janji buka juta lapangan kerja di ibu k...           61
2  banyak slot penerbangan internasional kosong i...           63
3  aturan wajib penggunaan kapal ri bisa ganggu e...           61
4      izin impor lelet waspada ekspor ri makin loyo           45

In [ ]:
# =========================
# WORD COUNT
# =========================
df['word_count'] = df['clean_text'].apply(lambda x: len(str(x).split()))

df[['clean_text', 'word_count']].head()

                                          clean_text  word_count
0  terbitkan resi pertama srg konawe bantu ketaha...           9
1  jokowi janji buka juta lapangan kerja di ibu k...          11
2  banyak slot penerbangan internasional kosong i...           8
3  aturan wajib penggunaan kapal ri bisa ganggu e...          10
4      izin impor lelet waspada ekspor ri makin loyo           8

In [ ]:
# =========================
# AVG WORD LENGTH
# =========================
df['avg_word_length'] = df['clean_text'].apply(
    lambda x: sum(len(word) for word in str(x).split()) / len(str(x).split()) if len(str(x).split()) > 0 else 0
)

df[['clean_text', 'avg_word_length']].head()

                                          clean_text  avg_word_length
0  terbitkan resi pertama srg konawe bantu ketaha...         6.333333
1  jokowi janji buka juta lapangan kerja di ibu k...         4.636364
2  banyak slot penerbangan internasional kosong i...         7.000000
3  aturan wajib penggunaan kapal ri bisa ganggu e...         5.200000
4      izin impor lelet waspada ekspor ri makin loyo         4.750000

In [ ]:
# =========================
# HASIL AKHIR TRANSFORMATION
# =========================
df.head()

,date,url,title,category,clean_text,text_length,word_count,avg_word_length
0,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...",finance,terbitkan resi pertama srg konawe bantu ketaha...,65,9,6.333333
1,02/26/2020,https://finance.detik.com/properti/d-4915865/j...,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,finance,jokowi janji buka juta lapangan kerja di ibu k...,61,11,4.636364
2,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Banyak Slot Penerbangan Internasional Kosong, ...",finance,banyak slot penerbangan internasional kosong i...,63,8,7.000000
3,02/26/2020,https://finance.detik.com/energi/d-4915883/atu...,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,finance,aturan wajib penggunaan kapal ri bisa ganggu e...,61,10,5.200000
4,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo",finance,izin impor lelet waspada ekspor ri makin loyo,45,8,4.750000

In [ ]:
# =========================
# SAVE DATA
# =========================
df.to_csv("dataset_pangan_transform.csv", index=False)

print("Dataset transformasi berhasil disimpan!")

Dataset transformasi berhasil disimpan!