<a href="https://colab.research.google.com/github/afllaabdi/tugas_NLP/blob/main/Source_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# =========================
# IMPORT LIBRARY
# =========================
import pandas as pd
import re

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
# =========================
# LOAD DATA
# =========================
file_path = '/content/drive/MyDrive/dataset/news_title_filter.csv'

df = pd.read_csv(file_path)

print("Jumlah data:", df.shape)
df.head()

Jumlah data: (4444, 4)

,date,url,title,category
0,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...",finance
1,02/26/2020,https://finance.detik.com/properti/d-4915865/j...,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,finance
2,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Banyak Slot Penerbangan Internasional Kosong, ...",finance
3,02/26/2020,https://finance.detik.com/energi/d-4915883/atu...,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,finance
4,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo",finance

In [6]:
# =========================
# DATA CLEANING
# =========================
# =========================
# COPY DATA
# =========================
df['clean_text'] = df['title']

df[['title', 'clean_text']].head()

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...","Terbitkan Resi Pertama, SRG Konawe Bantu Ketah..."
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...
2,"Banyak Slot Penerbangan Internasional Kosong, ...","Banyak Slot Penerbangan Internasional Kosong, ..."
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo","Izin Impor Lelet, Waspada Ekspor RI Makin Loyo"

In [7]:
# =========================
# LOWERCASE
# =========================
df['clean_text'] = df['clean_text'].str.lower()

df[['title', 'clean_text']].head()

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...","terbitkan resi pertama, srg konawe bantu ketah..."
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka 3 juta lapangan kerja di ibu...
2,"Banyak Slot Penerbangan Internasional Kosong, ...","banyak slot penerbangan internasional kosong, ..."
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,aturan wajib penggunaan kapal ri bisa ganggu e...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo","izin impor lelet, waspada ekspor ri makin loyo"

In [8]:
# =========================
# HAPUS NOISE
# =========================
df['clean_text'] = df['clean_text'].str.replace('video:', '', regex=False)
df['clean_text'] = df['clean_text'].str.replace('foto:', '', regex=False)

df[['title', 'clean_text']].head()

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...","terbitkan resi pertama, srg konawe bantu ketah..."
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka 3 juta lapangan kerja di ibu...
2,"Banyak Slot Penerbangan Internasional Kosong, ...","banyak slot penerbangan internasional kosong, ..."
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,aturan wajib penggunaan kapal ri bisa ganggu e...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo","izin impor lelet, waspada ekspor ri makin loyo"

In [9]:
# =========================
# HAPUS ANGKA
# =========================
df['clean_text'] = df['clean_text'].apply(lambda x: re.sub(r'\d+', '', x))

df[['title', 'clean_text']].head()

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...","terbitkan resi pertama, srg konawe bantu ketah..."
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka juta lapangan kerja di ibu ...
2,"Banyak Slot Penerbangan Internasional Kosong, ...","banyak slot penerbangan internasional kosong, ..."
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,aturan wajib penggunaan kapal ri bisa ganggu e...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo","izin impor lelet, waspada ekspor ri makin loyo"

In [10]:
# =========================
# HAPUS SIMBOL
# =========================
df['clean_text'] = df['clean_text'].apply(lambda x: re.sub(r'[^a-zA-Z\s]', '', x))

df[['title', 'clean_text']].head()

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...",terbitkan resi pertama srg konawe bantu ketaha...
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka juta lapangan kerja di ibu ...
2,"Banyak Slot Penerbangan Internasional Kosong, ...",banyak slot penerbangan internasional kosong i...
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,aturan wajib penggunaan kapal ri bisa ganggu e...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo",izin impor lelet waspada ekspor ri makin loyo

In [11]:
# =========================
# HAPUS SPASI
# =========================
df['clean_text'] = df['clean_text'].apply(lambda x: re.sub(r'\s+', ' ', x).strip())

df[['title', 'clean_text']].head()

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...",terbitkan resi pertama srg konawe bantu ketaha...
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka juta lapangan kerja di ibu k...
2,"Banyak Slot Penerbangan Internasional Kosong, ...",banyak slot penerbangan internasional kosong i...
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,aturan wajib penggunaan kapal ri bisa ganggu e...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo",izin impor lelet waspada ekspor ri makin loyo

In [12]:
# =========================
# HASIL AKHIR CLEANING
# =========================
df[['title', 'clean_text']].sample(10)

,title,clean_text
1632,"Anies Resmikan Operasi Pasar, Jaga Harga Bawan...",anies resmikan operasi pasar jaga harga bawang...
3192,Kapal Patroli PLP Kelas II Tual Bagikan Sembak...,kapal patroli plp kelas ii tual bagikan sembak...
1152,Harga Cabai di Kulon Progo Tembus Rp 80.000/Kg,harga cabai di kulon progo tembus rp kg
3761,PVMBG: Dentuman Dini Hari Ini Bukan Berasal da...,pvmbg dentuman dini hari ini bukan berasal dar...
738,Jokowi Siapkan Aturan Permudah Impor Barang Te...,jokowi siapkan aturan permudah impor barang te...
1745,Ketegangan AS-Iran Bikin Harga Emas Meroket,ketegangan asiran bikin harga emas meroket
1664,Mendag Klaim Harga Gula Sudah Turun Jadi Rp 14...,mendag klaim harga gula sudah turun jadi rp kg
494,Asyik! Ada ATM Beras Gratis di Bogor,asyik ada atm beras gratis di bogor
379,"Harga BBM Shell Turun, Lebih Murah Mana dengan...",harga bbm shell turun lebih murah mana dengan ...
3087,Langkah Bengkulu Halau Corona Lewati Pintu,langkah bengkulu halau corona lewati pintu

In [13]:
# =========================
# SAVE DATA
file_save_path = '/content/drive/MyDrive/dataset/dataset_pangan_cleaning.csv'

df.to_csv(file_save_path, index=False)

print("Dataset berhasil disimpan!")

Dataset berhasil disimpan!