<a href="https://colab.research.google.com/github/afllaabdi/tugas_NLP/blob/main/Source_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# =========================
# IMPORT LIBRARY
# =========================
import pandas as pd
import re

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# =======================
# LOAD DATA
# =========================
file_path = '/content/drive/MyDrive/dataset/news_title_filter.csv'

df = pd.read_csv(file_path)

print("Jumlah data:", df.shape)
df.head(5)

Jumlah data: (4444, 4)

,date,url,title,category
0,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...",finance
1,02/26/2020,https://finance.detik.com/properti/d-4915865/j...,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,finance
2,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Banyak Slot Penerbangan Internasional Kosong, ...",finance
3,02/26/2020,https://finance.detik.com/energi/d-4915883/atu...,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,finance
4,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo",finance

In [ ]:
# =========================
# DATA CLEANING
# =========================
# =========================
# COPY DATA
# =========================
df['clean_text'] = df['title']

df[['title', 'clean_text']].head()

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...","Terbitkan Resi Pertama, SRG Konawe Bantu Ketah..."
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...
2,"Banyak Slot Penerbangan Internasional Kosong, ...","Banyak Slot Penerbangan Internasional Kosong, ..."
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo","Izin Impor Lelet, Waspada Ekspor RI Makin Loyo"

In [ ]:
# =========================
# LOWERCASE
# =========================
df['clean_text'] = df['clean_text'].str.lower()

df[['title', 'clean_text']].head(100)

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...","terbitkan resi pertama, srg konawe bantu ketah..."
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka 3 juta lapangan kerja di ibu...
2,"Banyak Slot Penerbangan Internasional Kosong, ...","banyak slot penerbangan internasional kosong, ..."
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,aturan wajib penggunaan kapal ri bisa ganggu e...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo","izin impor lelet, waspada ekspor ri makin loyo"
...,...,...
95,"Harga Pangan Melonjak di Tengah Corona, Ini Bi...","harga pangan melonjak di tengah corona, ini bi..."
96,"Siasati Dampak Corona, Peternak Jual Ayam Door...","siasati dampak corona, peternak jual ayam door..."
97,"Surplus Sekitar 128.000 Ton, Persediaan Beras ...","surplus sekitar 128.000 ton, persediaan beras ..."
98,"Tak Perlu Keluar Rumah, Urus Izin Impor Pakan ...","tak perlu keluar rumah, urus izin impor pakan ..."
99,"Naik Rp 32.000, Harga Emas Makin Dekat Rp 1 Ju...","naik rp 32.000, harga emas makin dekat rp 1 ju..."

In [ ]:
# Hitung jumlah noise sebelum dihapus
jumlah_video = df['clean_text'].str.count('video:').sum()
jumlah_foto = df['clean_text'].str.count('foto:').sum()

print(f"Jumlah 'video:' sebelum dihapus: {jumlah_video}")
print(f"Jumlah 'foto:' sebelum dihapus: {jumlah_foto}")
print(f"Total noise: {jumlah_video + jumlah_foto}")

Jumlah 'video:' sebelum dihapus: 3
Jumlah 'foto:' sebelum dihapus: 8
Total noise: 11

In [ ]:
# =========================
# HAPUS NOISE
# =========================
df['clean_text'] = df['clean_text'].str.replace('video:', '', regex=False)
df['clean_text'] = df['clean_text'].str.replace('foto:', '', regex=False)

df[['title', 'clean_text']].head(5)

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...","terbitkan resi pertama, srg konawe bantu ketah..."
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka 3 juta lapangan kerja di ibu...
2,"Banyak Slot Penerbangan Internasional Kosong, ...","banyak slot penerbangan internasional kosong, ..."
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,aturan wajib penggunaan kapal ri bisa ganggu e...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo","izin impor lelet, waspada ekspor ri makin loyo"

In [ ]:
# =========================
# HAPUS ANGKA
# =========================
df['clean_text'] = df['clean_text'].apply(lambda x: re.sub(r'\d+', '', x))

df[['title', 'clean_text']].head()

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...","terbitkan resi pertama, srg konawe bantu ketah..."
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka juta lapangan kerja di ibu ...
2,"Banyak Slot Penerbangan Internasional Kosong, ...","banyak slot penerbangan internasional kosong, ..."
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,aturan wajib penggunaan kapal ri bisa ganggu e...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo","izin impor lelet, waspada ekspor ri makin loyo"

In [ ]:
# =========================
# HAPUS SIMBOL
# =========================
df['clean_text'] = df['clean_text'].apply(lambda x: re.sub(r'[^a-zA-Z\s]', '', x))

df[['title', 'clean_text']].head()

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...",terbitkan resi pertama srg konawe bantu ketaha...
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka juta lapangan kerja di ibu ...
2,"Banyak Slot Penerbangan Internasional Kosong, ...",banyak slot penerbangan internasional kosong i...
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,aturan wajib penggunaan kapal ri bisa ganggu e...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo",izin impor lelet waspada ekspor ri makin loyo

In [ ]:
# =========================
# HAPUS SPASI
# =========================
df['clean_text'] = df['clean_text'].apply(lambda x: re.sub(r'\s+', ' ', x).strip())

df[['title', 'clean_text']].head()

,title,clean_text
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...",terbitkan resi pertama srg konawe bantu ketaha...
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka juta lapangan kerja di ibu k...
2,"Banyak Slot Penerbangan Internasional Kosong, ...",banyak slot penerbangan internasional kosong i...
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,aturan wajib penggunaan kapal ri bisa ganggu e...
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo",izin impor lelet waspada ekspor ri makin loyo

In [ ]:
# =========================
# HASIL AKHIR CLEANING
# =========================
df[['title', 'clean_text']].sample(100)

,title,clean_text
1130,KKP Optimistis Sektor Perikanan Budi Daya Cipt...,kkp optimistis sektor perikanan budi daya cipt...
424,Begini Skenario di Lapangan Jika Mudik Jadi Di...,begini skenario di lapangan jika mudik jadi di...
2993,TNI-Polri Bagi Ratusan Sembako ke Warga Ciraca...,tnipolri bagi ratusan sembako ke warga ciracas...
2128,"Hobi Makan Daging Mentah, Otak Wanita Ini Dipe...",hobi makan daging mentah otak wanita ini dipen...
635,"Harga Minyak Anjlok, Trump Borong 75 Juta Barel",harga minyak anjlok trump borong juta barel
...,...,...
2649,Harga PS5 Bikin Patah Hati Kalau Benar Segini,harga ps bikin patah hati kalau benar segini
505,Mantap! Harga Emas Tembus Rp 850 Ribu Meski Di...,mantap harga emas tembus rp ribu meski digempu...
4253,"Beli Ducati Pakai Harga Off The Road, Gimana S...",beli ducati pakai harga off the road gimana su...
2869,Jokowi Tak Mau Pulangkan WNI Eks ISIS,jokowi tak mau pulangkan wni eks isis
3563,Ketua DPRD Surabaya Minta Pemkot Siapkan Angga...,ketua dprd surabaya minta pemkot siapkan angga...

In [ ]:
from IPython.display import display

# =========================
# HASIL AKHIR CLEANING (SAMPLE)
# =========================
print("=== HASIL CLEANING (SAMPLE) ===")
sample_df = df[['title', 'clean_text']].sample(n=min(5, len(df)), random_state=42).reset_index(drop=True)
display(sample_df)

# =========================
# BEFORE vs AFTER (4 DATA PERTAMA)
# =========================
print("\n=== BEFORE vs AFTER (4 DATA PERTAMA) ===")
before_after = df[['title', 'clean_text']].head(4).copy()
before_after.columns = ['before (title)', 'after (clean_text)']
display(before_after)

=== HASIL CLEANING (SAMPLE) ===

,title,clean_text
0,"Ikan Singgang hingga Opor Ayam, 5 Makanan Trad...",ikan singgang hingga opor ayam makanan tradisi...
1,Mensos Cek Kesiapan Implementasi Program Semba...,mensos cek kesiapan implementasi program semba...
2,4 Caddy Tangkap Buaya Muara 4 Meter di Lapanga...,caddy tangkap buaya muara meter di lapangan go...
3,Lebih dari 200 Ribu APD Didistribusikan ke Sel...,lebih dari ribu apd didistribusikan ke seluruh...
4,"Ada PSBB, Warga Jabodetabek Bakal Dapat Bantua...",ada psbb warga jabodetabek bakal dapat bantuan...

=== BEFORE vs AFTER (4 DATA PERTAMA) ===

,before (title),after (clean_text)
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...",terbitkan resi pertama srg konawe bantu ketaha...
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka juta lapangan kerja di ibu k...
2,"Banyak Slot Penerbangan Internasional Kosong, ...",banyak slot penerbangan internasional kosong i...
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,aturan wajib penggunaan kapal ri bisa ganggu e...

In [ ]:
# =========================
# SAVE DATA
file_save_path = '/content/drive/MyDrive/dataset/dataset_pangan_cleaning.csv'

df.to_csv(file_save_path, index=False)

print("Dataset berhasil disimpan!")

Dataset berhasil disimpan!

Tranformasi

In [ ]:
# =========================
# LOAD DATA
# =========================
file_path = '/content/drive/MyDrive/dataset/dataset_pangan_cleaning.csv'

df = pd.read_csv(file_path)

print("Jumlah data:", df.shape)
df.head(5)

Jumlah data: (4444, 5)

,date,url,title,category,clean_text
0,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...",finance,terbitkan resi pertama srg konawe bantu ketaha...
1,02/26/2020,https://finance.detik.com/properti/d-4915865/j...,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,finance,jokowi janji buka juta lapangan kerja di ibu k...
2,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Banyak Slot Penerbangan Internasional Kosong, ...",finance,banyak slot penerbangan internasional kosong i...
3,02/26/2020,https://finance.detik.com/energi/d-4915883/atu...,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,finance,aturan wajib penggunaan kapal ri bisa ganggu e...
4,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo",finance,izin impor lelet waspada ekspor ri makin loyo

In [ ]:
# =========================
# TEXT LENGTH
# =========================
df['text_length'] = df['clean_text'].apply(len)

df[['clean_text', 'text_length']].head()

                                          clean_text  text_length
0  terbitkan resi pertama srg konawe bantu ketaha...           65
1  jokowi janji buka juta lapangan kerja di ibu k...           61
2  banyak slot penerbangan internasional kosong i...           63
3  aturan wajib penggunaan kapal ri bisa ganggu e...           61
4      izin impor lelet waspada ekspor ri makin loyo           45

In [ ]:
# =========================
# WORD COUNT
# =========================
df['word_count'] = df['clean_text'].apply(lambda x: len(str(x).split()))

df[['clean_text', 'word_count']].head()

                                          clean_text  word_count
0  terbitkan resi pertama srg konawe bantu ketaha...           9
1  jokowi janji buka juta lapangan kerja di ibu k...          11
2  banyak slot penerbangan internasional kosong i...           8
3  aturan wajib penggunaan kapal ri bisa ganggu e...          10
4      izin impor lelet waspada ekspor ri makin loyo           8

In [ ]:
# =========================
# AVG WORD LENGTH
# =========================
df['avg_word_length'] = df['clean_text'].apply(
    lambda x: sum(len(word) for word in str(x).split()) / len(str(x).split()) if len(str(x).split()) > 0 else 0
)

df[['clean_text', 'avg_word_length']].head()

                                          clean_text  avg_word_length
0  terbitkan resi pertama srg konawe bantu ketaha...         6.333333
1  jokowi janji buka juta lapangan kerja di ibu k...         4.636364
2  banyak slot penerbangan internasional kosong i...         7.000000
3  aturan wajib penggunaan kapal ri bisa ganggu e...         5.200000
4      izin impor lelet waspada ekspor ri makin loyo         4.750000

In [ ]:
# =========================
# HASIL AKHIR TRANSFORMATION
# =========================
df.head()

,date,url,title,category,clean_text,text_length,word_count,avg_word_length
0,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...",finance,terbitkan resi pertama srg konawe bantu ketaha...,65,9,6.333333
1,02/26/2020,https://finance.detik.com/properti/d-4915865/j...,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,finance,jokowi janji buka juta lapangan kerja di ibu k...,61,11,4.636364
2,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Banyak Slot Penerbangan Internasional Kosong, ...",finance,banyak slot penerbangan internasional kosong i...,63,8,7.000000
3,02/26/2020,https://finance.detik.com/energi/d-4915883/atu...,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,finance,aturan wajib penggunaan kapal ri bisa ganggu e...,61,10,5.200000
4,02/26/2020,https://finance.detik.com/berita-ekonomi-bisni...,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo",finance,izin impor lelet waspada ekspor ri makin loyo,45,8,4.750000

In [ ]:
# =========================
# SAVE DATA
# =========================
df.to_csv("dataset_pangan_transform.csv", index=False)

print("Dataset transformasi berhasil disimpan!")

Dataset transformasi berhasil disimpan!

In [ ]:
from IPython.display import display

# =========================
# TEXT LENGTH
# =========================
df['text_length'] = df['clean_text'].apply(len)

print("=== TEXT LENGTH (SAMPLE) ===")
display(df[['clean_text', 'text_length']].head())

print("\n=== STATISTIK TEXT LENGTH ===")
display(df['text_length'].describe())

=== TEXT LENGTH (SAMPLE) ===

                                          clean_text  text_length
0  terbitkan resi pertama srg konawe bantu ketaha...           65
1  jokowi janji buka juta lapangan kerja di ibu k...           61
2  banyak slot penerbangan internasional kosong i...           63
3  aturan wajib penggunaan kapal ri bisa ganggu e...           61
4      izin impor lelet waspada ekspor ri makin loyo           45

=== STATISTIK TEXT LENGTH ===

count    4444.000000
mean       57.333258
std        11.254923
min        13.000000
25%        50.000000
50%        58.000000
75%        65.000000
max       103.000000
Name: text_length, dtype: float64

In [ ]:


# =========================
# WORD COUNT
# =========================
df['word_count'] = df['clean_text'].apply(lambda x: len(str(x).split()))

print("\n=== WORD COUNT (SAMPLE) ===")
display(df[['clean_text', 'word_count']].head())

print("\n=== STATISTIK WORD COUNT ===")
display(df['word_count'].describe())

=== WORD COUNT (SAMPLE) ===

                                          clean_text  word_count
0  terbitkan resi pertama srg konawe bantu ketaha...           9
1  jokowi janji buka juta lapangan kerja di ibu k...          11
2  banyak slot penerbangan internasional kosong i...           8
3  aturan wajib penggunaan kapal ri bisa ganggu e...          10
4      izin impor lelet waspada ekspor ri makin loyo           8

=== STATISTIK WORD COUNT ===

count    4444.000000
mean        9.036004
std         1.790907
min         2.000000
25%         8.000000
50%         9.000000
75%        10.000000
max        17.000000
Name: word_count, dtype: float64

In [ ]:


# =========================
# AVG WORD LENGTH
# =========================
df['avg_word_length'] = df['clean_text'].apply(
    lambda x: sum(len(word) for word in str(x).split()) / len(str(x).split()) if len(str(x).split()) > 0 else 0
)

print("\n=== AVG WORD LENGTH (SAMPLE) ===")
display(df[['clean_text', 'avg_word_length']].head())

print("\n=== STATISTIK AVG WORD LENGTH ===")
display(df['avg_word_length'].describe())

=== AVG WORD LENGTH (SAMPLE) ===

                                          clean_text  avg_word_length
0  terbitkan resi pertama srg konawe bantu ketaha...         6.333333
1  jokowi janji buka juta lapangan kerja di ibu k...         4.636364
2  banyak slot penerbangan internasional kosong i...         7.000000
3  aturan wajib penggunaan kapal ri bisa ganggu e...         5.200000
4      izin impor lelet waspada ekspor ri makin loyo         4.750000

=== STATISTIK AVG WORD LENGTH ===

count    4444.000000
mean        5.501797
std         0.773789
min         3.200000
25%         5.000000
50%         5.449495
75%         6.000000
max         9.142857
Name: avg_word_length, dtype: float64

In [ ]:

# =========================
# HASIL AKHIR TRANSFORMATION
# =========================
print("\n=== HASIL AKHIR TRANSFORMATION ===")
final_df = df[['title', 'clean_text', 'text_length', 'word_count', 'avg_word_length']].head()
display(final_df)

=== HASIL AKHIR TRANSFORMATION ===

,title,clean_text,text_length,word_count,avg_word_length
0,"Terbitkan Resi Pertama, SRG Konawe Bantu Ketah...",terbitkan resi pertama srg konawe bantu ketaha...,65,9,6.333333
1,Jokowi Janji Buka 3 Juta Lapangan Kerja di Ibu...,jokowi janji buka juta lapangan kerja di ibu k...,61,11,4.636364
2,"Banyak Slot Penerbangan Internasional Kosong, ...",banyak slot penerbangan internasional kosong i...,63,8,7.000000
3,Aturan Wajib Penggunaan Kapal RI Bisa Ganggu E...,aturan wajib penggunaan kapal ri bisa ganggu e...,61,10,5.200000
4,"Izin Impor Lelet, Waspada Ekspor RI Makin Loyo",izin impor lelet waspada ekspor ri makin loyo,45,8,4.750000

In [ ]:
from IPython.display import display
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# =========================
# 1. BAG OF WORDS (UNIGRAM)
# =========================
print("=== BAG OF WORDS (1-GRAM) ===")

bow = CountVectorizer(ngram_range=(1,1))
bow_matrix = bow.fit_transform(df['clean_text'])

bow_df = pd.DataFrame(bow_matrix.toarray(), columns=bow.get_feature_names_out())

display(bow_df.head())


# =========================
# 2. TF-IDF
# =========================
print("\n=== TF-IDF ===")

tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(df['clean_text'])

tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf.get_feature_names_out())

display(tfidf_df.head())


# =========================
# 3. BIGRAM (2-GRAM)
# =========================
print("\n=== BIGRAM (2-GRAM) ===")

bigram = CountVectorizer(ngram_range=(2,2))
bigram_matrix = bigram.fit_transform(df['clean_text'])

bigram_df = pd.DataFrame(bigram_matrix.toarray(), columns=bigram.get_feature_names_out())

display(bigram_df.head())


# =========================
# 4. TRIGRAM (3-GRAM)
# =========================
print("\n=== TRIGRAM (3-GRAM) ===")

trigram = CountVectorizer(ngram_range=(3,3))
trigram_matrix = trigram.fit_transform(df['clean_text'])

trigram_df = pd.DataFrame(trigram_matrix.toarray(), columns=trigram.get_feature_names_out())

display(trigram_df.head())

=== BAG OF WORDS (1-GRAM) ===

,abah,abaikan,abang,abangabang,abarth,abg,abidin,abigail,abipraya,abk,...,ziudith,zohri,zombie,zon,zona,zoological,zoom,zs,zuckerberg,zxr
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

=== TF-IDF ===

,abah,abaikan,abang,abangabang,abarth,abg,abidin,abigail,abipraya,abk,...,ziudith,zohri,zombie,zon,zona,zoological,zoom,zs,zuckerberg,zxr
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

=== BIGRAM (2-GRAM) ===

,abah disemayamkan,abaikan physical,abang dinsos,abang none,abang ojol,abangabang ala,abangabang yang,abarth si,abg di,abidin aceh,...,zombie ini,zon kritik,zon prabowo,zona merah,zoological garden,zoom kami,zs dengan,zs resmi,zuckerberg untuk,zxr segini
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

=== TRIGRAM (3-GRAM) ===

,abah disemayamkan di,abaikan physical distancing,abang dinsos sudah,abang none beri,abang ojol merasa,abangabang ala ayu,abangabang yang gurih,abarth si mungil,abg di tana,abidin aceh dipulangkan,...,zohri dkk dipulangkan,zombie ini hidup,zon kritik jokowi,zon prabowo bilang,zona merah corona,zoom kami salah,zs dengan honda,zs resmi meluncur,zuckerberg untuk covid,zxr segini bocoran
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# =========================
# TOP WORDS (UNIGRAM)
# =========================
word_counts = bow_matrix.sum(axis=0).A1
words = bow.get_feature_names_out()

top_words_df = pd.DataFrame({
    'word': words,
    'count': word_counts
}).sort_values(by='count', ascending=False)

print("\n=== TOP 10 KATA TERPOPULER ===")
display(top_words_df.head(10))

=== TOP 10 KATA TERPOPULER ===

         word  count
1212       di   1115
2087    harga   1069
1067   corona    643
2295      ini    596
5103       rp    496
1128      dan    416
2664       ke    377
6504     yang    342
5372  sembako    336
2256    impor    321